databases:
  - name: oxford_vtc_api_db
    plan: free
    databaseName: oxford_vtc_api_db
    user: oxford_vtc_api_user

services:
  - type: web
    plan: free
    name: oxford_vtc_api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Oxford_VTC_API.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars: 
      - key: DATABASE_URL
        fromDatabase: 
          name: oxford_vtc_api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
