# Generated by Django 4.2.11 on 2024-05-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='skills',
        ),
    ]
