# Generated by Django 4.2.11 on 2024-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
